### PR TITLE
Update welcomer.js

### PR DESCRIPTION
**Pull request by gurrrrrrrt**

### CODE REVIEW

**Review by jzeuzs — CHANGES_REQUESTED** [review]
This isn't necessary. It is an example welcomer, so users can add everything they want.

**Comment by Isaiah-Hamilton** [comment]
> This isn't necessary. It is an example welcomer, so users can add everything they want.

@1chiSensei your right. @CodeSuckss This file is to show people how to use moonstone and everything else in the example folder. You can make the examples more detailed and better explained if you want to contribute.

**Comment by gurrrrrrrt** [comment]
> > This isn't necessary. It is an example welcomer, so users can add everything they want.
> 
> @1chiSensei your right. @CodeSuckss This file is to show people how to use moonstone and everything else in the example folder. You can make the examples more detailed and better explained if you want to contribute.

okay

**Comment by itsfolf** [comment]
This file is meant simply as an example welcome bot, you can copy it and change it however you like. While this makes it easier for users understand how to customize it, it is expected that anyone who uses it has a basic understanding of javascript, making it useless.

**Pull request closed without merging**
